import type { Club, ClubEvent } from "@/types";

export const MOCK_CLUBS: Club[] = [
  {
    id: "1",
    name: "FC Kassel Nordstadt",
    category: "sport",
    location: "Kassel-Nordstadt",
    memberCount: 342,
    foundingYear: 1923,
    description:
      "Einer der ältesten Fußballvereine Kassels mit Angeboten für alle Altersgruppen – von der Bambini-Gruppe bis zu den Senioren.",
    tags: ["Fußball", "Jugend", "Kinder"],
    matchScore: 95,
    isOpenForAll: true,
    departments: [
      {
        id: "d1",
        name: "Junioren",
        memberCount: 48,
        ageRange: "6–18 Jahre",
        trainingTimes: ["Di 16:00–18:00", "Fr 16:00–18:00"],
        icon: "ball",
      },
      {
        id: "d2",
        name: "Herren",
        memberCount: 85,
        ageRange: "18+ Jahre",
        trainingTimes: ["Mo 19:00–21:00", "Mi 19:00–21:00"],
        icon: "ball",
      },
      {
        id: "d3",
        name: "Damen",
        memberCount: 62,
        ageRange: "18+ Jahre",
        trainingTimes: ["Di 18:00–20:00", "Do 18:00–20:00"],
        icon: "ball",
      },
      {
        id: "d4",
        name: "Senioren",
        memberCount: 38,
        ageRange: "50+ Jahre",
        trainingTimes: ["Mi 17:00–19:00"],
        icon: "ball",
      },
    ],
    events: [
      {
        id: "ce1",
        name: "Freundschaftsspiel vs. SV Baunatal",
        date: "2026-05-10T15:00:00",
        location: "Sportzentrum Nord",
        category: "Sport",
        isOpenForAll: true,
      },
      {
        id: "ce2",
        name: "Jahreshauptversammlung",
        date: "2026-05-18T19:00:00",
        location: "Vereinsheim Nordstadt",
        category: "Intern",
        isOpenForAll: false,
      },
    ],
    contact: {
      phone: "+49 561 12345678",
      email: "info@fc-kassel-nordstadt.de",
      website: "www.fc-kassel-nordstadt.de",
      address: "Sportzentrum Nord, Wilhelmshöher Allee 10, 34117 Kassel",
    },
    fees: [
      { group: "Erwachsene", price: 8 },
      { group: "Kinder/Jugendliche", price: 4 },
      { group: "Familien", price: 15 },
      { group: "Ermäßigt", price: 4 },
    ],
  },
  {
    id: "2",
    name: "Musikverein Kassel e.V.",
    category: "musik",
    location: "Kassel-Mitte",
    memberCount: 128,
    foundingYear: 1956,
    description:
      "Vom Blasorchester bis zum Kinderchor – Musik für alle. Wir freuen uns über Mitglieder aller Erfahrungsstufen und bieten gezielte Förderung.",
    tags: ["Musik", "Chor", "Orchester"],
    matchScore: 82,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {
      email: "kontakt@musikverein-kassel.de",
      website: "www.musikverein-kassel.de",
    },
    fees: [
      { group: "Erwachsene", price: 6 },
      { group: "Kinder/Jugendliche", price: 3 },
    ],
  },
  {
    id: "3",
    name: "Naturfreunde Kassel",
    category: "natur",
    location: "Kassel-Bettenhausen",
    memberCount: 89,
    foundingYear: 1912,
    description:
      "Wandern, Klettern und Naturschutz – wir erkunden gemeinsam die Region und fördern ein nachhaltiges Miteinander in der Gemeinschaft.",
    tags: ["Wandern", "Klettern", "Natur"],
    matchScore: 71,
    isOpenForAll: false,
    departments: [],
    events: [],
    contact: {
      email: "info@naturfreunde-kassel.de",
    },
    fees: [
      { group: "Erwachsene", price: 5 },
      { group: "Kinder/Jugendliche", price: 2.5 },
    ],
  },
  {
    id: "4",
    name: "Kulturzentrum Südstadt e.V.",
    category: "kultur",
    location: "Kassel-Südstadt",
    memberCount: 215,
    foundingYear: 1987,
    description:
      "Kunst, Theater und interkultureller Austausch – ein offener Ort für alle Menschen in Kassel. Workshops, Ausstellungen und Events das ganze Jahr.",
    tags: ["Kunst", "Theater", "Kultur"],
    matchScore: 68,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {
      email: "info@kulturzentrum-kassel.de",
      website: "www.kulturzentrum-kassel.de",
      phone: "+49 561 9876543",
    },
    fees: [
      { group: "Erwachsene", price: 7 },
      { group: "Kinder/Jugendliche", price: 3.5 },
      { group: "Ermäßigt", price: 4 },
    ],
  },
  {
    id: "5",
    name: "Familiensport Kassel Nord",
    category: "kinder",
    location: "Kassel-Kirchditmold",
    memberCount: 176,
    foundingYear: 2005,
    description:
      "Sport und Spiel für Familien – gemeinsam aktiv werden. Angebote für Eltern und Kinder von 2 bis 12 Jahren in entspannter Atmosphäre.",
    tags: ["Kinder", "Familie", "Sport"],
    matchScore: 88,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {
      email: "info@familiensport-kassel.de",
    },
    fees: [
      { group: "Familien", price: 12 },
      { group: "Einzelpersonen", price: 5 },
    ],
  },
  {
    id: "6",
    name: "Ehrenamtsnetzwerk Kassel",
    category: "ehrenamt",
    location: "Kassel-Mitte",
    memberCount: 304,
    foundingYear: 1998,
    description:
      "Wir vernetzen Ehrenamtliche und gemeinnützige Organisationen in Kassel. Engagement für alle – egal ob jung oder alt, erfahren oder neu.",
    tags: ["Ehrenamt", "Soziales", "Netzwerk"],
    matchScore: 60,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {
      email: "info@ehrenamt-kassel.de",
      website: "www.ehrenamt-kassel.de",
    },
    fees: [{ group: "Beitragsfrei", price: 0 }],
  },
];

export const MOCK_EVENTS: ClubEvent[] = [
  {
    id: "e1",
    name: "Freundschaftsspiel FC Kassel vs. SV Baunatal",
    date: "2026-05-10T15:00:00",
    location: "Sportzentrum Nord",
    category: "Sport",
    isOpenForAll: true,
    clubId: "1",
  },
  {
    id: "e2",
    name: "Frühjahrskonzert Musikverein",
    date: "2026-05-17T19:30:00",
    location: "Stadthalle Kassel",
    category: "Musik",
    isOpenForAll: true,
    clubId: "2",
  },
  {
    id: "e3",
    name: "Geführte Wanderung Habichtswald",
    date: "2026-05-24T09:00:00",
    location: "Treffpunkt Bergpark",
    category: "Natur",
    isOpenForAll: false,
    clubId: "3",
  },
];
