import type { Club, ClubEvent } from "@/types";

export const MOCK_CLUBS: Club[] = [
  {
    id: "m1",
    slug: "fc-kassel-nordstadt",
    name: "FC Kassel Nordstadt",
    category: "sport",
    location: "Kassel Nord",
    memberCount: 245,
    foundingYear: 1954,
    description: "Ein traditionsreicher Fußballverein mit Fokus auf Jugendarbeit.",
    tags: ["Fußball", "Jugend"],
    matchScore: 95,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m2",
    slug: "musikschule-mitte",
    name: "Musikschule Mitte",
    category: "musik",
    location: "Kassel Mitte",
    memberCount: 120,
    foundingYear: 1988,
    description: "Individueller Musikunterricht für alle Altersklassen.",
    tags: ["Klavier", "Gesang"],
    matchScore: 82,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m3",
    slug: "kletterzentrum-kassel",
    name: "Kletterzentrum Kassel",
    category: "sport",
    location: "Südstadt",
    memberCount: 500,
    foundingYear: 2010,
    description: "Klettern und Bouldern für Groß und Klein.",
    tags: ["Klettern", "Bouldern"],
    matchScore: 88,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m4",
    slug: "schachclub-kassel",
    name: "Schachclub Kassel",
    category: "sport",
    location: "Vorderer Westen",
    memberCount: 60,
    foundingYear: 1920,
    description: "Strategie und Konzentration für jedes Alter.",
    tags: ["Schach", "Denksport"],
    matchScore: 75,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m5",
    slug: "theater-kollektiv",
    name: "Theater Kollektiv",
    category: "kultur",
    location: "Nordstadt",
    memberCount: 25,
    foundingYear: 2015,
    description: "Experimentelles Theater und Performance-Kunst.",
    tags: ["Theater", "Kunst"],
    matchScore: 91,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m6",
    slug: "umweltgruppe-kassel",
    name: "Umweltgruppe Kassel",
    category: "natur",
    location: "Ganz Kassel",
    memberCount: 150,
    foundingYear: 1995,
    description: "Gemeinsam für ein grüneres Kassel.",
    tags: ["Umwelt", "Natur"],
    matchScore: 84,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m7",
    slug: "fotoclub-lichtblick",
    name: "Fotoclub Lichtblick",
    category: "kultur",
    location: "Mitte",
    memberCount: 40,
    foundingYear: 2005,
    description: "Die Welt durch die Linse entdecken.",
    tags: ["Fotografie", "Kunst"],
    matchScore: 78,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m8",
    slug: "tanzschule-rhythmus",
    name: "Tanzschule Rhythmus",
    category: "sport",
    location: "Bettenhausen",
    memberCount: 200,
    foundingYear: 2000,
    description: "Von Walzer bis Hip-Hop.",
    tags: ["Tanzen", "Musik"],
    matchScore: 89,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
  {
    id: "m9",
    slug: "handwerkshof",
    name: "Handwerkshof",
    category: "technik",
    location: "Kirchditmold",
    memberCount: 30,
    foundingYear: 2012,
    description: "Werkstatt für Holz- und Metallarbeiten.",
    tags: ["Handwerk", "DIY"],
    matchScore: 93,
    isOpenForAll: true,
    departments: [],
    events: [],
    contact: {},
    fees: [],
  },
];

export const MOCK_EVENTS: ClubEvent[] = [];
